### ISSUE TITLE
Scoring functins might have an issue

### ISSUE THREAD

**Issue by fzimmermann89** [CmrxRecon/CMRxRecon#11]
For example, 
in https://github.com/CmrxRecon/CMRxRecon/blob/df3f5a1abfcfcb75dbc371de66876184f8b70a1e/Evaluation/Evaluation.py#L65

is not how you usually calculate nMSE. Your implementation is extremely sensitive to a high-valued outlier in the prediction.
-> A single bright pixel somewhere can destroy the nMSE of an image.
The normalization should be done by the **ground truth** max.

The same issue and argument applies to PSNR and SSIM.

Please consider fixing this as it will influence the scoring somewhat arbitrarily.

**Comment by ChengYanHuPI** [comment]
Thank you for your suggestion. We appreciate your concerns and have discussed them among the organizing committee. However, we have decided not to modify the evaluation code for this challenge, and here are the main reasons for our decision:

    We aim to obtain results without outliers, and based on the current leaderboard rankings, this requirement seems achievable.
    Many teams have already familiarized themselves with and referenced our scoring rules. Modifying the rules at this stage would have an impact on many teams.

We understand your concerns and appreciate your understanding of our decision. If you have any further questions or suggestions, please feel free to let us know.

Best regards,
CMRxRecon Team

**Comment by fzimmermann89** [comment]
Thank you for your consideration, we understand that a change this late in the challenge would unfairly shuffle the results.
