### ISSUE TITLE
some doubt about the mat file in submission

### ISSUE THREAD

**Issue by hannah-zhangzz** [CmrxRecon/CMRxRecon#12]
I'm confused, the cine_sax.mat and cine_lax.mat which I need to submit, should be in the image domain or k-space domain? If in image domain, should the data range be 0~255 or 0~1?

**Comment by ChengYanHuPI** [comment]
You should submit the images in spatial domain. 
Please refer to the reconstruction demo code we provided: https://github.com/CmrxRecon/CMRxRecon/tree/main/CMRxReconDemo.
