### ISSUE TITLE
why the workflow failed

### ISSUE THREAD

**Issue by Zhangzl0304** [CmrxRecon/CMRxRecon#13]
when I submit the file to task 2, the workflow can be finished. But the file is for cine(task 1) and I organized the file names the same as the example. The job cannot be finished if I submit it to task 1. Why??

**Comment by ziqiangxu** [comment]
> when I submit the file to task 2, the workflow can be finished. But the file is for cine(task 1) and I organized the file names the same as the example. The job cannot be finished if I submit it to task 1. Why??

Could you please share the file to hyikesong on synapse？So I can reproduce this issue and investigate it thoroughly.

**Comment by Zhangzl0304** [comment]
Thanks for your reply. The issue has been solved.
