### ISSUE TITLE
Availability of Full-Sampled Validation and Test Sets

### ISSUE THREAD

**Issue by yhao-z** [CmrxRecon/CMRxRecon#15]
I have recently explored the excellent CMRxRecon dataset and, while I understand the intentional omission of fully-sampled validation and test sets during the challenge to ensure fairness, I am reaching out to inquire about the possibility of releasing the complete full-sampled data for the validation and test sets now that the competition has successfully concluded.

I believe that making the full-sampled data available could significantly contribute to the advancement of the dynamic magnetic resonance imaging reconstruction community. Researchers and practitioners alike would greatly benefit from having access to this additional resource, fostering further exploration, analysis, and improvement of reconstruction techniques.

**Comment by ChengYanHuPI** [comment]
According to the rules of our challenge, we will share the gold standard data of all the competitions with all fully participating teams (docker submitted) early next month. Last week, we have reached out to the relevant participating teams via email to inquire about their preferred way of data sharing.

For teams that did not participate in the competition in full, we plan to make all data fully available to the public after 6~8 months. We kindly ask for your understanding in this matter.

**Comment by yhao-z** [comment]
yes, totally understand. Thanks a lot!
