### ISSUE TITLE
whether the ground truth of  validation set will be made available

### ISSUE THREAD

**Issue by hannah-zhangzz** [CmrxRecon/CMRxRecon#17]
Hello! I have noticed that the leaderboard has recently been closed. In the officially designated trainset, validation set, and testset, currently only the input and ground truth for the trainset are available, while the validation set only has the input data, and there is no access to the testset at all. I would like to know if the validation set and testset will be made available in the future.  Looking forward to your response！

**Comment by ChengYanHuPI** [comment]
According to the rules of our challenge, we have shared the gold standard data of all the competitions with all fully participating teams (docker submitted) last month. 

For teams that did not participate in the competition in full, we plan to make all data fully available to the public later. We kindly ask for your understanding in this matter.
