### ISSUE TITLE
Submission Format for Python

### ISSUE THREAD

**Issue by calderds** [CmrxRecon/CMRxRecon#2]
MATLAB files appear to be given in v7.3 which are readable in python, but very hard to write. Are files compatible with MATLAB <v7.2 (such as output of `scipy.io.savemat()`) accepted, or can some sample code be provided to write v7.3 mat files in python?

**Comment by ChengYanHuPI** [comment]
We suggest you to use ‘h5py’ for reading and writing. 
The demo scripts have been provided in our GitHub link: https://github.com/CmrxRecon/CMRxRecon/tree/main/Evaluation <https://github.com/CmrxRecon/CMRxRecon/tree/main/Evaluation> 

Best regards,
CMRxRecon Team

**Comment by calderds** [comment]
Thanks for the response! I saw the code to write files in MainLoadFun.py.

**Comment by Breeze-Zero** [comment]
I notice that h5py reads the dimensions [time,sz,sx,sy], while mat73, sigpy, and matlab read the dimensions [sy,sx,sz,time](in reverse order).If the read function uses h5py, why does the evaluation function use the last two dimensions as time and sz?

**Comment by ChengYanHuPI** [comment]
The issue has been resolved. Please try resubmitting the task.

Best regards,
CMRxRecon Team

2023年6月13日 21:53，Breeze. ***@***.***> 写道：



I notice that h5py reads the dimensions [time,sz,sx,sy], while mat73, sigpy, and matlab read the dimensions [sy,sx,sz,time](in reverse order).If the read function uses h5py, why does the evaluation function use the last two dimensions as time and sz?
