### ISSUE TITLE
Issue with the cropping

### ISSUE THREAD

**Issue by fzimmermann89** [CmrxRecon/CMRxRecon#7]
Hi there, sorry for bothering you...

We are struggling to get the cropping for validation right. Our detailed log contains many files listed under '"different_sizes":  with no metrics.

Would it maybe be possible to adjust the code you run in the submission runner to also print the shapes of dataset1 and dataset2 in case of a missmatch, such that this info then appears in the standard log file?

I.e. adding a 
`print(dataset1.shape,dataset2.shape)` at https://github.com/CmrxRecon/CMRxRecon/blob/8b67d3118bc1107c9103a0fc279c030973c65471/Evaluation/Main_Score.py#L206
would already help us.

Judging by the number of logs containing the different_sizes issue for submissions by other teams, this would generally be helpful to many participant..

Thanks!

**Comment by ziqiangxu** [comment]
The code running in the evaluation server can be found here, 
https://github.com/ziqiangxu/CMRxRecon-Task1-Valid/blob/master/Docker/Main_Score.py

I will add this line to the server version.

**Comment by ziqiangxu** [comment]
This code is added and deployed, and you can add more logs here, I will deploy it within a day.

https://github.com/ziqiangxu/CMRxRecon-Task1-Valid/blob/38577c7f4a68e33523699352cb27bf7efb5780cf/Docker/Main_Score.py#L207C1-L214C25

**Comment by ziqiangxu** [comment]
The detail log can be found in: https://www.synapse.org/#!Synapse:syn51756002, named by {submission_id}.zip, 
and the logger's output is wrote into file "custom_log.txt", "custom_log.txt" can be found in {submission_id}.zip.

**Comment by fzimmermann89** [comment]
Thank you so much !!

**Comment by fzimmermann89** [comment]
Thank you so much !!
